In [7]:
print("to jest pierwszy notebook")

to jest pierwszy notebook


# otwarcie notebooka

In [8]:
a = 200
print(a)

200


In [9]:
b = 87
c = a+b
print(c)

287


# To jest ważne narzędzie do <span style="color:red; font-family:Impact;">**projektowania**</span> i <span style="color:green; font-family:Impact;">**wizualizacji**</span> modeli AI

In [14]:
lsztuk = 5

In [15]:
cena = "4.5"

In [17]:
lsztuk*float(cena)

22.5

In [18]:
import numpy as np

In [19]:
np.zeros(33)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
u = np.arange(1,89,2)
u

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
 69, 71, 73, 75, 77, 79, 81, 83, 85, 87])

In [21]:
m = np.array([[6,8],[7,3]])
m

array([[6, 8],
 [7, 3]])

In [25]:
a1 = np.arange(15).reshape(5,3)
a1

array([[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11],
 [12, 13, 14]])

In [26]:
a2 = np.arange(27).reshape(3,3,3)
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])